import { ApplicationConfig, importProvidersFrom } from "@angular/core";
import { provideRouter, withViewTransitions } from "@angular/router";
import { routes } from "./app.routes";
import {
	AlignLeft,
	Blocks,
	CalendarDays,
	CheckCheck,
	CheckCheckIcon,
	ExternalLink,
	GitBranch,
	Globe,
	GraduationCap,
	Layers,
	Linkedin,
	LucideAngularModule,
	MapPin,
	Mic,
	MoveRight,
	Network,
	PianoIcon,
	Presentation,
	RefreshCw,
	Sparkles,
	Spool,
	Star,
	Ticket,
	TrendingUp,
	TriangleAlert,
	Twitter,
	Users,
	Wrench,
	XIcon,
} from "lucide-angular";
import { provideHttpClient, withFetch } from "@angular/common/http";

export const AppConfig: ApplicationConfig = {
	providers: [
		provideHttpClient(withFetch()),
		provideRouter(routes, withViewTransitions()),
		importProvidersFrom(
			LucideAngularModule.pick({
				AlignLeft,
				Linkedin,
				XIcon,
				MoveRight,
				ExternalLink,
				PianoIcon,
				Spool,
				Network,
				CalendarDays,
				CheckCheck,
				Blocks,
				GitBranch,
				Globe,
				GraduationCap,
				Layers,
				MapPin,
				Mic,
				Presentation,
				RefreshCw,
				Sparkles,
				Star,
				Ticket,
				TrendingUp,
				TriangleAlert,
				Twitter,
				Users,
				Wrench,
			}),
		),
	],
};
