import { ApplicationConfig } from "@angular/core";
import { provideRouter, withViewTransitions } from "@angular/router";
import {
	AlignLeft,
	CalendarClock,
	CalendarDays,
	CalendarPlus,
	CheckCheck,
	Clock,
	Download,
	ExternalLink,
	GitBranch,
	Globe,
	GraduationCap,
	Hourglass,
	Layers,
	MapPin,
	Network,
	Presentation,
	RefreshCw,
	Spool,
	Star,
	Ticket,
	TrendingUp,
	TriangleAlert,
	Users,
	Wrench,
	X,
} from "lucide";
import { routes } from "./app.routes";
import { linkedinIcon, xTwitterIcon } from "./shared/icons/brand-icons";
import { provideIcons } from "./shared/icons/icon-registry";

export const AppConfig: ApplicationConfig = {
	providers: [
		provideRouter(routes, withViewTransitions()),
		provideIcons({
			"align-left": AlignLeft,
			"calendar-clock": CalendarClock,
			"calendar-days": CalendarDays,
			"calendar-plus": CalendarPlus,
			"check-check": CheckCheck,
			clock: Clock,
			download: Download,
			"external-link": ExternalLink,
			"git-branch": GitBranch,
			globe: Globe,
			"graduation-cap": GraduationCap,
			hourglass: Hourglass,
			layers: Layers,
			linkedin: linkedinIcon,
			"map-pin": MapPin,
			network: Network,
			presentation: Presentation,
			"refresh-cw": RefreshCw,
			spool: Spool,
			star: Star,
			ticket: Ticket,
			"trending-up": TrendingUp,
			"triangle-alert": TriangleAlert,
			users: Users,
			wrench: Wrench,
			x: X,
			"x-twitter": xTwitterIcon,
		}),
	],
};
